import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "../components/TopNav"

const inter = Inter({ subsets: ["latin"] });

type ImageProps = {
  imgSrc: string,
  imgText: string,
  imgClass: string,
  imgContainer: string
}
interface ButtonProps {
  buttonUrl: string,
  buttonSlug: string,
  buttonClass: string,
  slugClass: string
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
  }) {
  
  const profileImage = {
    imgSrc: "https://placehold.co/120x120",
    imgContainer: "imageContainer",
    imgText: "profile picture",
    imgClass: "rounded"
  }

  const listClass = "navButtonList"

  const navList = [{
    buttonUrl: "/About",
    buttonSlug: "About Me",
    buttonClass: "button",
    slugClass: "navButtonSlug"
  }, {
    buttonUrl: "/Projects",
    buttonSlug: "Projects",
    buttonClass: "button",
    slugClass: "navButtonSlug"
  }, {
    buttonUrl: "/Contact",
    buttonSlug: "Contact Me",
    buttonClass: "button",
    slugClass: "navButtonSlug"
  }];
  return (
    <html lang="en" className="min-h-vh sm:h-full">
      <body className={`${inter.className} min-h-vh sm:h-full`}>
        <main className="h-full">
          {/* separate out Nav as separate component */}
          <TopNav
            buttonProps={navList}
            imageProps={profileImage}
            listCLass={listClass}
          />
          <section className="flex flex-grow h-full">
            {/* Social links sidebar; separate out as separate component; also separate out each link as component with image prop */}
            <div className="min-w-[120px] bg-slate-600">Social Links</div>
            <div className="p-4 bg-gradient-to-br from-sky-900 via-sky-700 to-sky-500 navBorder">{children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
