import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "../components/top-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const profileImage = {
    src: "https://placehold.co/120x120",
    text: "profile picture",
  };

  const navList = [
    {
      url: "/about",
      slug: "About Me",
    },
    {
      url: "/projects",
      slug: "Projects",
    },
    {
      url: "/contact",
      slug: "Contact Me",
    },
  ];
  return (
    <html lang="en" className="min-h-vh sm:h-full">
      <body className={`${inter.className} min-h-vh sm:h-full`}>
        <main className="h-full">
          {/* separate out Nav as separate component */}
          <TopNav links={navList} img={profileImage} />
          <section className="flex flex-grow h-full">
            {/* Social links sidebar; separate out as separate component; also separate out each link as component with image prop */}
            <div className="min-w-[120px] bg-slate-600">Social Links</div>
            <div className="p-4 bg-gradient-to-br from-sky-900 via-sky-700 to-sky-500 navBorder">
              {children}
            </div>
          </section>
          <footer className="flex bg-red-600 footer justify-center w-screen absolute h-screen">class</footer>
        </main>
      </body>
    </html>
  );
}
